print("BENVENUTI IN --IL SEGRETO DEL TELETRASPORTO-- ")
print()
print("Ti svegli, è una mattina come tante: fai colazione, ti lavi denti e faccia")
print("e come sempre ti prepari per andare a scuola.")
print("Arrivato a scuola attendi con ansia il suono della campanella finale, ma durante l'intervallo")
print("intravedi la bidella che per sbaglio lascia aperta una porta sempre sigillata.")
print("Dubbioso ti avvicini e...")
print()
print("1. Apri la porta")
print("2. Vai a raccontare tutto ai tuoi amici")
print()
risp1 = int(input())
print()
if risp1 == 1:
	print("Ti avvicini alla porta e sei pronto per entare.")
else:
	print("Corri in classe a raccontare tutto prima che l'intervallo finisca.")
print("I tuoi amici ti raggiungono e, sopraffatti dalla curiosità aprite la porta ed entrate.")
print("Non trovate l'intrruttore della luce, è buio: Riky decide di accendere la torcia del telefono.")
print("Purtroppo tutti i cellulari si spengono misteriosamente, ma nel buio si intavede una luce fioca")
print("Avvicindovi gli occhi si abituano alla luminosità e tu riesci a intravedere un pulsante rosso.")
print()
print("1. Premi il pulsante")
print("2. L'intervallo sta per finire e vi avviate per tornare in classe")
print()
risp2 = int(input())
print()
if risp2 == 1:
	print("Coraggiosamente premi il pulsante insieme ai tuoi amici")
else:
	print("Vi avviate per tornare in classe. All'improvviso Jack,")
	print("il più vivace del gruppo, preme il bottone.")
print("Si alza un forte vento all'interno della stanza, si apre un portale e venite risucchiati.")
print()
print("Siete sulla luna")
print("Non riuscite neanche ad ambientarvi quando il portale si chiude alle vostre spalle.")
print("Impauriti cercate vi consultate e decidete cosa fare:")
print()
print("1. Decidete di cercare un nuovo portale")
print("2. Date una gran festa sulla luna")
print()
risp3 = int(input())
print()
if risp3 == 1:
	print("Iniziate a camminare, ma di un nuovo portale non c'è traccia.")
	print("Giunti ad un profondo cratere vi sembra di intravedere una luce al suo interno")
	print("Cosa decidete?")
	print()
	print("1. Vi gettate nel cratere")
	print("2. Vi avviate alla ricerca di una via più sicura")
	print()
	risp4 = int(input())
	if risp4 == 1:
		print("Mentre state cadendo vi rendete conto che la luce proviene")
		print("in realtà da un meteorite radioattivo.")
		print("Con un gesto eroico riesci ad afferrare la mano dei tuoi comagni")
		print("e ad aggrapparti al bordo del cratere:")
	else:
		print("Sbadatamente Riki scivola, Jack riesce ad afferrarlo ma inizia")
		print("a precipitare anche lui.")
		print("Con un gesto eroico riesci ad afferrare la mano del tuo compagno")
		print("e ad aggrapparti al bordo del cratere:")
	print("Non sai per quanto potrai resistere.")
else:
	print("Comincia la gran festa e iniziate a ballare")
print()
print("PREMI TASTO r PER continuare")
print()
a = input()
if a == "r":
	print("Improvvisamente tutto sparisce e siete accecati da una luce splendente.")
	print("Quando iniziate ad intravedere qualcosa riconoscete il professore")
	print("di Informatica che vi illustra il nuovo progetto scolastico")
	print("sviluppato da uno studente universitario sulla realtà virtuale.")